### ISSUE TITLE
Validity of cache (Feature Request)

### ISSUE THREAD

**Issue by kalle2000** [b-jesch/script.module.pvr.artwork#3]
Can you add the option of "unlimited" to the cache function?

**Comment by b-jesch** [comment]
PVR artwork module writes always back to the cache, e.g. if a record is read this will be updated and rewritten to cache. In this case the lifetime of this record will be renewed for the next complete cycle and lifetime never ends - except for those entries who wasn't update within the lifetime cycle.

In my opinion there is no reason for an unlimited option. Or is there another reason?

**Comment by kalle2000** [comment]
Alright, then I misunderstood that setting.
I wanted to make sure that artwork (once downloaded) is cleared and re-read again.

**Comment by b-jesch** [comment]
You can only clear downloaded artwork within the maintenance settings (or manual deleting). Downloaded artwork has a higher priority then online artwork.

**Comment by kalle2000** [comment]
works as desired :)
